### PR TITLE
Added the source ip to the req object

### PR DESCRIPTION
**Pull request by TonyWael**

### CODE REVIEW

**Comment by watson** [comment]
@TonyWael thanks for your pull request - highly appreciated 😃

The tests are unfortunately failing. Please have a look and update the PR

**Comment by watson** [comment]
@TonyWael Any reason why you closed this PR?

**Comment by TonyWael** [comment]
Hi @watson

I closer this one because the test failed, i fixed the issue and updated the readme and created a new pr.

**Comment by watson** [comment]
@TonyWael You can always update an existing PR by pushing or rebasing the commits on the branch. A PR is tied to a branch, so whatever commits are contained in the branch will be visible in the PR 😃

**Pull request closed without merging**
