### PR TITLE
Added the source ip to the req object.

### PR DESCRIPTION
**Pull request by TonyWael**

### CODE REVIEW

**Comment by TonyWael** [comment]
README updated for the req ip

**Comment by watson** [comment]
@TonyWael didn't see this PR for some reason - thanks! After merging I found a bug in Node v4. I'll just fix that before publishing to npm

**Comment by TonyWael** [comment]
Hi @watson ,

I downloaded your library using NPM today however i still did not find the ip that i added to the req object. Do you happen to know when you will you publish the changes to NPM?

Kind regards, 
Tony

**Comment by watson** [comment]
Ups, it's now published as v2.0.0 on npm 😃

**Pull request merged**
